linters:
  enable-all: true
  disable:
    # unused linters
    - depguard
    - gochecknoglobals
    - gochecknoinits
    - errcheck
    - gomnd
    - exhaustruct
    - gofumpt
    - wsl
    - nlreturn
    - varnamelen
    - tagalign
    - tagliatelle
    - lll
    - funlen
    - interfacebloat
    - dupl
    # deprecated linters
    - varcheck
    - interfacer
    - deadcode
    - exhaustivestruct
    - ifshort
    - maligned
    - scopelint
    - golint
    - nosnakecase
    - structcheck
  fast: false
