linters:
  enable-all: true
  disable:
    # unused linters
    - depguard
    - gochecknoglobals
    - gochecknoinits
    - errcheck
    - gomnd
    - exhaustruct
    # deprecated linters
    - varcheck
    - interfacer
    - deadcode
    - exhaustivestruct
    - ifshort
    - maligned
    - scopelint
    - golint
    - nosnakecase
    - structcheck
  fast: false
