# only for development
# use repo SQL-Online-Judge/deploy for production

version: '3'

services:
  mongo:
    image: mongo:7
    restart: always
    volumes:
      - dev_mongodata:/data/db
    ports:
      - 27017:27017

  redis:
    image: redis:7
    restart: always
    ports:
      - 6379:6379

  core:
    build:
      context: ./
      dockerfile: ./cmd/core/Dockerfile
    image: SQL-Online-Judge/backend/core
    restart: on-failure
    env_file:
      - ./configs/core.env
    depends_on:
      - mongo
      - redis
    ports:
      - 3000:3000

volumes:
  dev_mongodata:
